import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react';
import logo from '../assets/NONICOMS.png'
import HomeSection from '../component/sections/Home'

export default function Home() {
    function windowScroll() {
        const navbar = document.getElementById("navbar");
        if (
            document.body.scrollTop >= 50 ||
            document.documentElement.scrollTop >= 50
        ) {
            navbar?.classList.add("nav-sticky");
        } else {
            navbar?.classList.remove("nav-sticky");
        }
      }
      
      useEffect(() => {
        window.addEventListener('scroll', (ev) => {
            ev.preventDefault();
            windowScroll();
          })
      }, [])
      
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
      </Head>
      {/* <Navbar/> */}
    <nav className="navbar navbar-expand-lg fixed-top navbar-custom sticky sticky-dark nav-sticky" id="navbar">
        <div className="container">
            <a className="navbar-brand logo text-uppercase" href="index.html">
                {/* <i className="mdi mdi-alien"></i>Hiric */}
                <Image alt='' src={logo} width={60} height={60} />
            </a>


            <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <i className="mdi mdi-menu"></i>
            </button>

            <div className="collapse navbar-collapse" id="navbarCollapse">
                <ul className="navbar-nav navbar-center" id="navbar-navlist">
                    <li className="nav-item">
                        <a data-scroll="" href="#home" className="nav-link">Home</a>
                    </li>
                    <li className="nav-item">
                        <a data-scroll="" href="#features" className="nav-link">Packages</a>
                    </li>
                    <li className="nav-item">
                        <a data-scroll="" href="#services" className="nav-link">Services</a>
                    </li>
                    <li className="nav-item">
                        <a data-scroll="" href="#about" className="nav-link">About</a>
                    </li>
                    <li className="nav-item active">
                        <a data-scroll="" href="#pricing" className="nav-link active">Pricing</a>
                    </li>
                    {/* <li className="nav-item">
                        <a data-scroll="" href="#blog" className="nav-link">Blog</a>
                    </li> */}
                    <li className="nav-item">
                        <a data-scroll="" href="#contact" className="nav-link">Contact</a>
                    </li>

                </ul>
                <div className="nav-button ms-auto">
                    <ul className="nav navbar-nav navbar-right">
                        <li>
                            <button type="button" className="btn btn-primary navbar-btn btn-rounded waves-effect waves-light">Try it
                                Free</button>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>

    <section className="section bg-home home-half home-registration" id="home">
        <div className="bg-overlay"></div>
        <div className="display-table">
            <div className="display-table-cell">
                <div className="container">
                    <div className="row vertical-content">
                        <div className="col-lg-7 text-white text-start">
                            <div className="mt-4">
                                <h4 className="home-small-title">NONICOMMS</h4>
                                <h1 className="home-title">Fast internet connection</h1>
                                <p className="pt-3 home-desc home-subtitle-width-100">State of the art reliable internet for your Home and Office use,
                                through high speed broadband of more than 100mbps at an unbeatable price that addresses everyday communication challenges in homes and businesses.
                                </p>
                                <a href="#" className="btn btn-primary mt-5 waves-effect waves-light">Get Started <i className="mdi mdi-arrow-right"></i></a>
                            </div>
                        </div>
                        <div className="col-lg-4 offset-lg-1">
                        <div className="home-registration-form bg-white mt-4">
                                <h4 className="form-heading text-center mt-2">Get a FREE Quote</h4>
                                <form className="registration-form" id="registration-form">
                                    <input type="text" id="exampleInputName1" className="form-control registration-input-box" placeholder="Name"/>
                                    <input type="email" id="exampleInputEmail1" className="form-control registration-input-box" placeholder="Email"/>
                                    <textarea className="form-control registration-textarea-box" rows={4} placeholder="Message"></textarea>
                                    <button className="btn btn-primary w-100 waves-effect waves-light">Send Detail</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
  

    <section className="section-sm bg-light">
        <div className="container">
            <div className="row">
                <div className="col-md-3">
                    <div className="client-images my-3 my-md-0">
                        {/* <img src="" alt="logo-img" className="mx-auto img-fluid d-block"/> */}
                    </div>
                </div>
                <div className="col-md-3">
                    <div className="client-images my-3 my-md-0">
                        {/* <img src="images/clients/2.png" alt="logo-img" className="mx-auto img-fluid d-block"> */}
                    </div>
                </div>
                <div className="col-md-3 ">
                    <div className="client-images my-3 my-md-0">
                        {/* <img src="images/clients/3.png" alt="logo-img" className="mx-auto img-fluid d-block"> */}
                    </div>
                </div>
                <div className="col-md-3">
                    <div className="client-images my-3 my-md-0">
                        {/* <img src="images/clients/4.png" alt="logo-img" className="mx-auto img-fluid d-block"> */}
                    </div>
                </div>
            </div>
        </div>
    </section>
   
    <section className="section" id="features">
        <div className="container">
            <div className="row align-items-center">
                <div className="col-lg-5 order-2 order-lg-1">
                    <div className="features-box mt-5 mt-lg-0">
                        <h3>Providing Quality &amp Internet Service.</h3>
                        <p className="text-muted web-desc">Leveraging High speed Internet by creating a stream of reliable 
                        and affordable internet based solutions </p>
                        <ul className="text-muted list-unstyled mt-4 features-item-list">
                            <li className="">High speed fibre internet.</li>
                            <li className="">IPTV/Ondemad Content.</li>
                            <li className="">VOIP/VoWiFi/Wi-Fi.</li>
                        </ul>
                        <a href="#" className="btn btn-primary mt-4 waves-effect waves-light">Learn More <i className="mdi mdi-arrow-right"></i></a>
                    </div>
                </div>
                <div className="col-lg-7 order-1 order-lg-2">
                    <div className="features-img mx-auto me-lg-0">
                        <img src="https://themesbrand.com/hiric/layout/images/growth-analytics.svg" alt="macbook image" className="img-fluid"/>
                    </div>
                </div>
            </div>
        </div>
    </section>
   
    <section className="section bg-light" id="services">
        <div className="container">
            <div className="row">
                <div className="col-lg-8 offset-lg-2">
                    <h1 className="section-title text-center">Our Services</h1>
                    <div className="section-title-border mt-3"></div>
                    <p className="section-subtitle text-muted text-center pt-4 font-secondary">Through high speed
                     broadband of more than 100mbps at an 
                    unbeatable price that addresses everyday communication challenges in homes and businesses..</p>
                </div>
            </div>
            <div className="row mt-5">
                <div className="col-lg-4 mt-4">
                    <div className="services-box">
                        <div className="d-flex">
                            <i className="pe-7s-diamond text-primary"></i>
                            <div className="ms-4">
                                <h4>VOIP/Telephone/Intercom</h4>
                                <p className="pt-2 text-muted">Our subsriptions comes with free unlimited voice call 
                                to all nonicoms to nonicoms users and minimal cost to other users</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="col-lg-4 mt-4">
                    <div className="services-box">
                        <div className="d-flex">
                            <i className="pe-7s-display2 text-primary"></i>
                            <div className="ms-4">
                                <h4>IPTV/OTT</h4>
                                <p className="pt-2 text-muted">With live streaming of HD/4k visual clarity. our subsribers
                                can enjoy free unrestricted access to multiple programs.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="col-lg-4 mt-4">
                    <div className="services-box">
                        <div className="d-flex">
                            <i className="pe-7s-piggy text-primary"></i>
                            <div className="ms-4">
                                <h4>Networking services</h4>
                                <p className="pt-2 text-muted">Proven solutions for network transformation, tools and templates.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="row">
                <div className="col-lg-4 mt-4">
                    <div className="services-box">
                        <div className="d-flex">
                            <i className="pe-7s-science text-primary"></i>
                            <div className="ms-4">
                                <h4>Optimize</h4>
                                <p className="pt-2 text-muted">Technical expertise that helps deliver network insigths and evolve your network's capabilities.</p>
                            </div>
                        </div>
                    </div>
                </div>
                {/* <div className="col-lg-4 mt-4">
                    <div className="services-box">
                        <div className="d-flex">
                            <i className="pe-7s-news-paper text-primary"></i>
                            <div className="ms-4">
                                <h4>Truly Multipurpose</h4>
                                <p className="pt-2 text-muted">Even the all-powerful Pointing has no control about the blind
                                    texts it is an almost unorthographic.</p>
                            </div>
                        </div>
                    </div>
                </div> */}
                {/* <div className="col-lg-4 mt-4">
                    <div className="services-box">
                        <div className="d-flex">
                            <i className="pe-7s-plane text-primary"></i>
                            <div className="ms-4">
                                <h4>Easy to customize</h4>
                                <p className="pt-2 text-muted">Question Marks and devious Semikoli, but the Little Blind
                                    Text didnt listen. She packed her seven versalia.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div> */}

            {/* <div className="row">
                <div className="col-lg-4 mt-4">
                    <div className="services-box">
                        <div className="d-flex">
                            <i className="pe-7s-arc text-primary"></i>
                            <div className="ms-4">
                                <h4>Pixel Perfect Design</h4>
                                <p className="pt-2 text-muted">There are many variations of passages of Lorem Ipsum
                                    available, but the majority have suffered alteration.</p>
                            </div>
                        </div>
                    </div>
                </div> */}
                {/* <div className="col-lg-4 mt-4">
                    <div className="services-box">
                        <div className="d-flex">
                            <i className="pe-7s-tools text-primary"></i>
                            <div className="ms-4">
                                <h4>Perfect Toolbox</h4>
                                <p className="pt-2 text-muted">Hampden-Sydney College in Virginia, looked up one of the more
                                    obscure Latin words, consectetur.</p>
                            </div>
                        </div>
                    </div>
                </div> */}
                {/* <div className="col-lg-4 mt-4">
                    <div className="services-box">
                        <div className="d-flex">
                            <i className="pe-7s-timer text-primary"></i>
                            <div className="ms-4">
                                <h4>Awesome Design</h4>
                                <p className="pt-2 text-muted">All the Lorem Ipsum generators on the Internet tend to repeat
                                    predefined chunks as necessary.</p>
                            </div>
                        </div>
                    </div>
                </div> */}
            </div>
        </div>
    </section>
   
    <section className="section bg-web-desc">
        <div className="bg-overlay"></div>
        <div className="container">
            <div className="row">
                <div className="col-lg-12 text-center">
                    <h2 className="text-white">Build your dream website today</h2>
                    <p className="pt-3 home-desc mx-auto">But nothing the copy said could convince her and so it didn’t take
                        long until a few insidious Copy Writers ambushed her.</p>
                    <a href="#" className="btn btn-white mt-5 waves-effect waves-light">View Plan &amp; Pricing</a>
                </div>
            </div>
        </div>
    </section>
 
    <section className="section" id="about">
        <div className="container">
            <div className="row">
                <div className="col-lg-8 offset-lg-2">
                    <div className="about-title mx-auto text-center">
                        <h2>A Digital web studio creating stunning &amp; Engaging online
                            Experiences </h2>
                        <p className="text-muted pt-4">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
                            commodo ligula eget dolor.
                            Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur
                            ridiculus mus donec various versions have evolved quam felis.</p>
                    </div>
                </div>
            </div>
            <div className="row mt-5">
                <div className="col-lg-3 col-sm-6">
                    <div className="team-box text-center">
                        <div className="team-wrapper">
                            <div className="team-member">
                                {/* <img alt="" src="images/team/img-1.jpg" className="img-fluid rounded"> */}
                            </div>
                        </div>
                        <h4 className="team-name">Frank Johnson</h4>
                        <p className="text-uppercase team-designation">CEO</p>
                    </div>
                </div>

                <div className="col-lg-3 col-sm-6">
                    <div className="team-box text-center">
                        <div className="team-wrapper">
                            <div className="team-member">
                                {/* <img alt="" src="images/team/img-2.jpg" className="img-fluid rounded"> */}
                            </div>
                        </div>
                        <h4 className="team-name">Elaine Stclair</h4>
                        <p className="text-uppercase team-designation">Designer</p>
                    </div>
                </div>

                <div className="col-lg-3 col-sm-6">
                    <div className="team-box text-center">
                        <div className="team-wrapper">
                            <div className="team-member">
                                {/* <img alt="" src="images/team/img-3.jpg" className="img-fluid rounded"> */}
                            </div>
                        </div>
                        <h4 className="team-name">Wanda Arthur</h4>
                        <p className="text-uppercase team-designation">Developer</p>
                    </div>
                </div>

                <div className="col-lg-3 col-sm-6">
                    <div className="team-box text-center">
                        <div className="team-wrapper">
                            <div className="team-member">
                                {/* <img alt="" src="images/team/img-4.jpg" className="img-fluid rounded"> */}
                            </div>
                        </div>
                        <h4 className="team-name">Joshua Stemple</h4>
                        <p className="text-uppercase team-designation">Manager</p>
                    </div>
                </div>

            </div>
        </div>
    </section>

    <section className="section bg-light active" id="pricing">
        <div className="container">
            <div className="row">
                <div className="col-lg-8 offset-lg-2">
                    <h1 className="section-title text-center">Our Pricing</h1>
                    <div className="section-title-border mt-3"></div>
                    <p className="section-subtitle font-secondary text-muted text-center pt-4">Call to action pricing table
                        is really crucial to your for your business website. Make your bids stand-out with amazing
                        options.</p>
                </div>
            </div>
            <div className="row mt-5">
                <div className="col-lg-4">
                    <div className="text-center pricing-box">
                        <h4 className="text-uppercase">Economy</h4>
                        <h1>$9.90</h1>
                        <h6 className="text-uppercase text-muted">Billing Per Month</h6>
                        <div className="plan-features mt-5">
                            <p>Bandwidth: <b className="text-primary">1GB</b></p>
                            <p>Onlinespace: <b className="text-primary">50MB</b></p>
                            <p>Support: <b className="text-primary">No</b></p>
                            <p><b className="text-primary">1</b> Domain</p>
                            <p><b className="text-primary">No</b> Hidden Fees</p>
                        </div>
                        <a href="#" className="btn btn-primary waves-effect waves-light mt-5">Join Now</a>
                    </div>
                </div>
                <div className="col-lg-4">
                    <div className="text-center pricing-box bg-white price-active">
                        <div className="ribbon-box"><span>Popular</span></div>
                        <h4 className="text-uppercase">Deluxe</h4>
                        <h1>$19.90</h1>
                        <h6 className="text-uppercase text-muted">Billing Per Month</h6>
                        <div className="plan-features mt-5">
                            <p>Bandwidth: <b className="text-primary">10GB</b></p>
                            <p>Onlinespace: <b className="text-primary">500MB</b></p>
                            <p>Support: <b className="text-primary">Yes</b></p>
                            <p><b className="text-primary">10</b> Domain</p>
                            <p><b className="text-primary">No</b> Hidden Fees</p>
                        </div>
                        <a href="#" className="btn btn-primary waves-effect waves-light mt-5">Join Now</a>
                    </div>
                </div>
                <div className="col-lg-4">
                    <div className="text-center pricing-box">
                        <h4 className="text-uppercase">Ultimate</h4>
                        <h1>$29.90</h1>
                        <h6 className="text-uppercase text-muted">Billing Per Month</h6>
                        <div className="plan-features mt-5">
                            <p>Bandwidth: <b className="text-primary">100GB</b></p>
                            <p>Onlinespace: <b className="text-primary">2 GB</b></p>
                            <p>Support: <b className="text-primary">Yes</b></p>
                            <p><b className="text-primary">Unlimited</b> Domain</p>
                            <p><b className="text-primary">No</b> Hidden Fees</p>
                        </div>
                        <a href="#" className="btn btn-primary waves-effect waves-light mt-5">Join Now</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
  
    <section className="section" id="testi">
        <div className="container">
            <div className="row">
                <div className="col-lg-8 offset-lg-2">
                    <h1 className="section-title text-center">What they have said</h1>
                    <div className="section-title-border mt-3"></div>
                    <p className="section-subtitle text-muted text-center font-secondary pt-4">The Big Oxmox advised her not
                        to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli.
                    </p>
                </div>
            </div>
            <div className="row mt-5">
                <div className="col-lg-4">
                    <div className="testimonial-box mt-4">
                        <div className="testimonial-decs p-4">
                            <div className="testi-icon">
                                <i className="mdi mdi-format-quote-open display-1"></i>
                            </div>
                            {/* <img src="images/testimonials/user-1.jpg" alt="" className="img-fluid mx-auto d-block img-thumbnail rounded-circle mb-4"> */}
                            <div className="p-1">
                                <h5 className="text-center text-uppercase mb-3">Dennis Williams - <span className="text-muted text-capitalize">Charleston</span></h5>
                                <p className="text-muted text-center mb-0">“I feel confident imposing change on myself. It is
                                    a lot more fun progressing than
                                    looking back. That is why I ultricies enim at malesuada nibh diam on tortor neaded to
                                    throw curve balls.” </p>
                            </div>
                        </div>

                    </div>
                </div>
                <div className="col-lg-4">
                    <div className="testimonial-box mt-4">
                        <div className="testimonial-decs p-4">
                            <div className="testi-icon">
                                <i className="mdi mdi-format-quote-open display-1"></i>
                            </div>
                            {/* <img src="images/testimonials/user-2.jpg" alt="" className="img-fluid mx-auto d-block img-thumbnail rounded-circle mb-4"> */}
                            <div className="p-1">
                                <h5 className="text-center text-uppercase mb-3">Laurie Bell - <span className="text-muted text-capitalize">Worcester</span></h5>
                                <p className="text-muted text-center mb-0">“Our task must be to free ourselves by widening
                                    our circle of compassion to embrace
                                    all living creatures and the whole of quis consectetur nunc sit amet semper justo.
                                    nature and its beauty.” </p>
                            </div>
                        </div>

                    </div>
                </div>
                <div className="col-lg-4">
                    <div className="testimonial-box mt-4">
                        <div className="testimonial-decs p-4">
                            <div className="testi-icon">
                                <i className="mdi mdi-format-quote-open display-1"></i>
                            </div>
                            {/* <img src="images/testimonials/user-3.jpg" alt="" className="img-fluid mx-auto d-block img-thumbnail rounded-circle mb-4"> */}
                            <div className="p-1">
                                <h5 className="text-center text-uppercase mb-3">Howard Kelley - <span className="text-muted text-capitalize">Lynchburg</span></h5>
                                <p className="text-muted text-center mb-0">“I have learned that people will forget what you
                                    said, people will forget what you did,
                                    but people will never forget how donec in efficitur lectus, nec lobortis metus you
                                    made them feel.” </p>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>

    <section className="section section-lg bg-get-start">
        <div className="bg-overlay"></div>
        <div className="container">
            <div className="row">
                <div className="col-lg-8 offset-lg-2 text-center">
                    <h1 className="get-started-title text-white">Lets Get Started</h1>
                    <div className="section-title-border mt-4 bg-white"></div>
                    <p className="section-subtitle font-secondary text-white text-center pt-4">Far far away, behind the word
                        mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                    <a href="#" className="btn btn-white waves-effect mt-4">Get Started <i className="mdi mdi-arrow-right"></i>
                    </a>
                </div>
            </div>
        </div>
    </section>
   
    <section className="section bg-light" id="blog">
        <div className="container">
            <div className="row">
                <div className="col-lg-8 offset-lg-2">
                    <h1 className="section-title text-center">Latest News</h1>
                    <div className="section-title-border mt-3"></div>
                    <p className="section-subtitle text-muted text-center font-secondary pt-4">Separated they live in
                        Bookmarksgrove right at the coast of the Semantics, a large language ocean class at a euismod
                        mus luctus quam.</p>
                </div>
            </div>

            <div className="row mt-4">
                <div className="col-lg-4">
                    <div className="blog-box mt-4">
                        <img src="images/blog/img-1.jpg" className="img-fluid rounded" alt=""/>
                        <div>
                            <h5 className="mt-4 text-muted">UI &amp; UX Design</h5>
                            <h4 className="mt-3"><a href="" className="blog-title"> Doing a cross country road trip </a></h4>
                            <p className="text-muted">She packed her seven versalia, put her initial into the belt and made
                                herself on the way..</p>
                            <div className="mt-3">
                                <a href="" className="read-btn">Read More <i className="mdi mdi-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="col-lg-4">
                    <div className="blog-box mt-4">
                        <img src="images/blog/img-2.jpg" className="img-fluid rounded" alt=""/>
                        <div>
                            <h5 className="mt-4 text-muted">Digital Marketing</h5>
                            <h4 className="mt-3"><a href="" className="blog-title">New exhibition at our Museum</a></h4>
                            <p className="text-muted">Pityful a rethoric question ran over her cheek, then she continued her
                                way.</p>
                            <div className="mt-3">
                                <a href="" className="read-btn">Read More <i className="mdi mdi-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="col-lg-4">
                    <div className="blog-box mt-4">
                        {/* <img src="images/blog/img-3.jpg" className="img-fluid rounded" alt=""> */}
                        <div>
                            <h5 className="mt-4 text-muted">Travelling</h5>
                            <h4 className="mt-3"><a href="" className="blog-title">Why are so many people..</a></h4>
                            <p className="text-muted">Far far away, behind the word mountains, far from the countries
                                Vokalia and Consonantia.</p>
                            <div className="mt-3">
                                <a href="" className="read-btn">Read More <i className="mdi mdi-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </section>
    
    <section className="section" id="contact">
        <div className="container">
            <div className="row">
                <div className="col-lg-8 offset-lg-2">
                    <h1 className="section-title text-center">Get In Touch</h1>
                    <div className="section-title-border mt-3"></div>
                    <p className="section-subtitle text-muted text-center font-secondary pt-4">We thrive when coming up with
                        innovative ideas but also understand that a smart concept should be supported with faucibus
                        sapien odio measurable
                        results.</p>
                </div>
            </div>
            <div className="row">
                <div className="col-lg-4">
                    <div className="mt-4 pt-4">
                        <p className="mt-4"><span className="h5">Office Address 1:</span><br/> <span className="text-muted d-block mt-2">4461 Cedar Street Moro, AR 72368</span></p>
                        <p className="mt-4"><span className="h5">Office Address 2:</span><br/> <span className="text-muted d-block mt-2">2467 Swick Hill Street <br/>New Orleans, LA
                                70171</span></p>
                        <p className="mt-4"><span className="h5">Working Hours:</span><br/> <span className="text-muted d-block mt-2">9:00AM To 6:00PM</span></p>
                    </div>
                </div>
                <div className="col-lg-8">
                    <div className="custom-form mt-4 pt-4">
                        <form method="post" name="myForm" >
                            <p id="error-msg"></p>
                            <div id="simple-msg"></div>
                            <div className="row">
                                <div className="col-lg-6">
                                    <div className="form-group mt-2">
                                        <input name="name" id="name" type="text" className="form-control" placeholder="Your name*"/>
                                    </div>
                                </div>
                                <div className="col-lg-6">
                                    <div className="form-group mt-2">
                                        <input name="email" id="email" type="email" className="form-control" placeholder="Your email*"/>
                                    </div>
                                </div>
                            </div>
                            <div className="row">
                                <div className="col-lg-12">
                                    <div className="form-group mt-2">
                                        <input type="text" className="form-control" id="subject" placeholder="Your Subject.."/>
                                    </div>
                                </div>
                            </div>
                            <div className="row">
                                <div className="col-lg-12">
                                    <div className="form-group mt-2">
                                        <textarea name="comments" id="comments" rows={4} className="form-control" placeholder="Your message..."></textarea>
                                    </div>
                                </div>
                            </div>
                            <div className="row">
                                <div className="col-lg-12 text-end">
                                    <input type="submit" id="submit" name="send" className="submitBnt btn btn-primary" value="Send Message"/>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <footer className="footer">
        <div className="container">
            <div className="row">
                <div className="col-lg-3 mt-4">
                    <h4>HIRIC</h4>
                    <div className="text-muted mt-4">
                        <ul className="list-unstyled footer-list">
                            <li><a href="#">Home</a></li>
                            <li><a href="#">About us</a></li>
                            <li><a href="#">Careers</a></li>
                            <li><a href="#">Contact us</a></li>
                        </ul>
                    </div>
                </div>
                <div className="col-lg-3 mt-4">
                    <h4>Information</h4>
                    <div className="text-muted mt-4">
                        <ul className="list-unstyled footer-list">
                            <li><a href="#">Terms &amp; Condition</a></li>
                            <li><a href="#">About us</a></li>
                            <li><a href="#">Jobs</a></li>
                            <li><a href="#">Bookmarks</a></li>
                        </ul>
                    </div>
                </div>
                <div className="col-lg-3 mt-4">
                    <h4>Support</h4>
                    <div className="text-muted mt-4">
                        <ul className="list-unstyled footer-list">
                            <li><a href="">FAQ</a></li>
                            <li><a href="">Contact</a></li>
                            <li><a href="">Disscusion</a></li>
                        </ul>
                    </div>
                </div>
                <div className="col-lg-3 mt-4">
                    <h4>Subscribe</h4>
                    <div className="text-muted mt-4">
                        <p>In an ideal world this text wouldn’t exist, a client would acknowledge the importance of
                            having web copy before the design starts.</p>
                    </div>
                    <form className="form subscribe">
                        <input placeholder="Email" className="form-control" required/>
                        <a href="#" className="submit"><i className="pe-7s-paper-plane"></i></a>
                    </form>
                </div>
            </div>
        </div>
    </footer>

    {/* <div className="footer-alt">
        <div className="container">
            <div className="row">
                <div className="col-lg-12">
                    <div className="float-start pull-none">
                        <p className="copy-rights text-muted mb-3 mb-sm-0">
                            <script>
                                document.write(new Date().getFullYear())
                            </script>2022 © Hiric - Themesbrand
                        </p>
                    </div>
                    <div className="float-end pull-none ">
                        <ul className="list-inline d-flex flex-wrap social m-0">
                            <li className="list-inline-item"><a href="" className="social-icon"><i className="mdi mdi-facebook"></i></a></li>
                            <li className="list-inline-item"><a href="" className="social-icon"><i className="mdi mdi-twitter"></i></a></li>
                            <li className="list-inline-item"><a href="" className="social-icon"><i className="mdi mdi-linkedin"></i></a></li>
                            <li className="list-inline-item"><a href="" className="social-icon"><i className="mdi mdi-google-plus"></i></a></li>
                            <li className="list-inline-item"><a href="" className="social-icon"><i className="mdi mdi-microsoft-xbox"></i></a></li>
                        </ul>
                    </div>
                    <div className="clearfix"></div>
                </div>
            </div>
        </div>
    </div> */}

  
 




      {/* <HomeSection/> */}
      {/* <section className="section-sm bg-light">
        <div className="container">
            <div className="row">
                <div className="col-md-3">
                    <div className="client-images my-3 my-md-0">
                        <img src="https://themesbrand.com/hiric/layout/images/clients/1.png" alt="logo-img" className="mx-auto img-fluid d-block"/>
                    </div>
                </div>

                <div className="col-md-3">
                    <div className="client-images my-3 my-md-0">
                        <img src="https://themesbrand.com/hiric/layout/images/clients/1.png" alt="logo-img" className="mx-auto img-fluid d-block"/>
                    </div>
                </div>

                <div className="col-md-3 ">
                    <div className="client-images my-3 my-md-0">
                        <img src="https://themesbrand.com/hiric/layout/images/clients/1.png" alt="logo-img" className="mx-auto img-fluid d-block"/>
                    </div>
                </div>

                <div className="col-md-3">
                    <div className="client-images my-3 my-md-0">
                        <img src="https://themesbrand.com/hiric/layout/images/clients/1.png" alt="logo-img" className="mx-auto img-fluid d-block"/>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section className="section2" id="features">
        <div className="container">
            <div className="row align-items-center">
                <div className="col-lg-5 order-2 order-lg-1">
                    <div className="features-box mt-5 mt-lg-0">
                        <h3>A digital web design studio creating modern &amp; engaging online</h3>
                        <p className="text-muted web-desc">Separated they live in Bookmarksgrove right at the coast of the
                            Semantics, a large language ocean.</p>
                        <ul className="text-muted list-unstyled mt-4 features-item-list">
                            <li className="">We put a lot of effort in design.</li>
                            <li className="">The most important ingredient of successful website.</li>
                            <li className="">Submit Your Orgnization.</li>
                        </ul>
                        <a href="#" className="btn btn-primary mt-4 waves-effect waves-light">Learn More <i className="mdi mdi-arrow-right"></i></a>
                    </div>
                </div>
                <div className="col-lg-7 order-1 order-lg-2">
                    <div className="features-img mx-auto me-lg-0">
                        <img src="https://themesbrand.com/hiric/layout/images/growth-analytics.svg" alt="macbook image" className="img-fluid"/>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section className="section2 bg-light" id="services">
        <div className="container">
            <div className="row">
                <div className="col-lg-8 offset-lg-2">
                    <h1 className="section-title text-center">Our Services</h1>
                    <div className="section-title-border mt-3"></div>
                    <p className="section-subtitle text-muted text-center pt-4 font-secondary">We craft digital, graphic and
                        dimensional thinking, to create category leading brand experiences that have meaning and add a
                        value for our clients.</p>
                </div>
            </div>
            <div className="row mt-5">
                <div className="col-lg-4 mt-4">
                    <div className="services-box">
                        <div className="d-flex">
                            <i className="pe-7s-diamond text-primary"></i>
                            <div className="ms-4">
                                <h4>Digital Design</h4>
                                <p className="pt-2 text-muted">Some quick example text to build on the card title and make
                                    up the bulk of the card's content. Moltin gives platform.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="col-lg-4 mt-4">
                    <div className="services-box">
                        <div className="d-flex">
                            <i className="pe-7s-display2 text-primary"></i>
                            <div className="ms-4">
                                <h4>Unlimited Colors</h4>
                                <p className="pt-2 text-muted">Credibly brand standards compliant users without extensible
                                    services. Anibh euismod tincidunt laoreet Ipsum passage.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="col-lg-4 mt-4">
                    <div className="services-box">
                        <div className="d-flex">
                            <i className="pe-7s-piggy text-primary"></i>
                            <div className="ms-4">
                                <h4>Strategy Solutions</h4>
                                <p className="pt-2 text-muted">Separated they live in Bookmarksgrove right at the coast of
                                    the Semantics, and large language ocean neary regelia.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="row">
                <div className="col-lg-4 mt-4">
                    <div className="services-box">
                        <div className="d-flex">
                            <i className="pe-7s-science text-primary"></i>
                            <div className="ms-4">
                                <h4>Awesome Support</h4>
                                <p className="pt-2 text-muted">It is a paradisematic country, in which roasted parts of
                                    sentences fly into your mouth leave for the far World.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="col-lg-4 mt-4">
                    <div className="services-box">
                        <div className="d-flex">
                            <i className="pe-7s-news-paper text-primary"></i>
                            <div className="ms-4">
                                <h4>Truly Multipurpose</h4>
                                <p className="pt-2 text-muted">Even the all-powerful Pointing has no control about the blind
                                    texts it is an almost unorthographic.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="col-lg-4 mt-4">
                    <div className="services-box">
                        <div className="d-flex">
                            <i className="pe-7s-plane text-primary"></i>
                            <div className="ms-4">
                                <h4>Easy to customize</h4>
                                <p className="pt-2 text-muted">Question Marks and devious Semikoli, but the Little Blind
                                    Text didn’t listen. She packed her seven versalia.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div className="row">
                <div className="col-lg-4 mt-4">
                    <div className="services-box">
                        <div className="d-flex">
                            <i className="pe-7s-arc text-primary"></i>
                            <div className="ms-4">
                                <h4>Pixel Perfect Design</h4>
                                <p className="pt-2 text-muted">There are many variations of passages of Lorem Ipsum
                                    available, but the majority have suffered alteration.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="col-lg-4 mt-4">
                    <div className="services-box">
                        <div className="d-flex">
                            <i className="pe-7s-tools text-primary"></i>
                            <div className="ms-4">
                                <h4>Perfect Toolbox</h4>
                                <p className="pt-2 text-muted">Hampden-Sydney College in Virginia, looked up one of the more
                                    obscure Latin words, consectetur.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="col-lg-4 mt-4">
                    <div className="services-box">
                        <div className="d-flex">
                            <i className="pe-7s-timer text-primary"></i>
                            <div className="ms-4">
                                <h4>Awesome Design</h4>
                                <p className="pt-2 text-muted">All the Lorem Ipsum generators on the Internet tend to repeat
                                    predefined chunks as necessary.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section className="section2 bg-web-desc">
        <div className="bg-overlay"></div>
        <div className="container">
            <div className="row">
                <div className="col-lg-12 text-center">
                    <h2 className="text-white">Build your dream website today</h2>
                    <p className="pt-3 home-desc mx-auto">But nothing the copy said could convince her and so it didn’t take
                        long until a few insidious Copy Writers ambushed her.</p>
                    <a href="#" className="btn btn-white mt-5 waves-effect waves-light">View Plan &amp; Pricing</a>
                </div>
            </div>
        </div>
    </section>
    
    <section className="section2 active" id="about">
        <div className="container">
            <div className="row">
                <div className="col-lg-8 offset-lg-2">
                    <div className="about-title mx-auto text-center">
                        <h2>A Digital web studio creating stunning &amp; Engaging online
                            Experiences </h2>
                        <p className="text-muted pt-4">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
                            commodo ligula eget dolor.
                            Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur
                            ridiculus mus donec various versions have evolved quam felis.</p>
                    </div>
                </div>
            </div>
            <div className="row mt-5">
                <div className="col-lg-3 col-sm-6">
                    <div className="team-box text-center">
                        <div className="team-wrapper">
                            <div className="team-member">
                                <img alt="" src="https://themesbrand.com/hiric/layout/images/team/img-1.jpg" className="img-fluid rounded"/>
                            </div>
                        </div>
                        <h4 className="team-name">Frank Johnson</h4>
                        <p className="text-uppercase team-designation">CEO</p>
                    </div>
                </div>

                <div className="col-lg-3 col-sm-6">
                    <div className="team-box text-center">
                        <div className="team-wrapper">
                            <div className="team-member">
                                <img alt="" src="https://themesbrand.com/hiric/layout/images/team/img-1.jpg" className="img-fluid rounded"/>
                            </div>
                        </div>
                        <h4 className="team-name">Elaine Stclair</h4>
                        <p className="text-uppercase team-designation">Designer</p>
                    </div>
                </div>

                <div className="col-lg-3 col-sm-6">
                    <div className="team-box text-center">
                        <div className="team-wrapper">
                            <div className="team-member">
                                <img alt="" src="https://themesbrand.com/hiric/layout/images/team/img-1.jpg" className="img-fluid rounded"/>
                            </div>
                        </div>
                        <h4 className="team-name">Wanda Arthur</h4>
                        <p className="text-uppercase team-designation">Developer</p>
                    </div>
                </div>

                <div className="col-lg-3 col-sm-6">
                    <div className="team-box text-center">
                        <div className="team-wrapper">
                            <div className="team-member">
                                <img alt="" src="https://themesbrand.com/hiric/layout/images/team/img-1.jpg" className="img-fluid rounded"/>
                            </div>
                        </div>
                        <h4 className="team-name">Joshua Stemple</h4>
                        <p className="text-uppercase team-designation">Manager</p>
                    </div>
                </div>

            </div>
        </div>
    </section>

    <section className="section bg-light" id="pricing">
        <div className="container">
            <div className="row">
                <div className="col-lg-8 offset-lg-2">
                    <h1 className="section-title text-center">Our Pricing</h1>
                    <div className="section-title-border mt-3"></div>
                    <p className="section-subtitle font-secondary text-muted text-center pt-4">Call to action pricing table
                        is really crucial to your for your business website. Make your bids stand-out with amazing
                        options.</p>
                </div>
            </div>
            <div className="row mt-5">
                <div className="col-lg-4">
                    <div className="text-center pricing-box">
                        <h4 className="text-uppercase">Economy</h4>
                        <h1>$9.90</h1>
                        <h6 className="text-uppercase text-muted">Billing Per Month</h6>
                        <div className="plan-features mt-5">
                            <p>Bandwidth: <b className="text-primary">1GB</b></p>
                            <p>Onlinespace: <b className="text-primary">50MB</b></p>
                            <p>Support: <b className="text-primary">No</b></p>
                            <p><b className="text-primary">1</b> Domain</p>
                            <p><b className="text-primary">No</b> Hidden Fees</p>
                        </div>
                        <a href="#" className="btn btn-primary waves-effect waves-light mt-5">Join Now</a>
                    </div>
                </div>
                <div className="col-lg-4">
                    <div className="text-center pricing-box bg-white price-active">
                        <div className="ribbon-box"><span>Popular</span></div>
                        <h4 className="text-uppercase">Deluxe</h4>
                        <h1>$19.90</h1>
                        <h6 className="text-uppercase text-muted">Billing Per Month</h6>
                        <div className="plan-features mt-5">
                            <p>Bandwidth: <b className="text-primary">10GB</b></p>
                            <p>Onlinespace: <b className="text-primary">500MB</b></p>
                            <p>Support: <b className="text-primary">Yes</b></p>
                            <p><b className="text-primary">10</b> Domain</p>
                            <p><b className="text-primary">No</b> Hidden Fees</p>
                        </div>
                        <a href="#" className="btn btn-primary waves-effect waves-light mt-5">Join Now</a>
                    </div>
                </div>
                <div className="col-lg-4">
                    <div className="text-center pricing-box">
                        <h4 className="text-uppercase">Ultimate</h4>
                        <h1>$29.90</h1>
                        <h6 className="text-uppercase text-muted">Billing Per Month</h6>
                        <div className="plan-features mt-5">
                            <p>Bandwidth: <b className="text-primary">100GB</b></p>
                            <p>Onlinespace: <b className="text-primary">2 GB</b></p>
                            <p>Support: <b className="text-primary">Yes</b></p>
                            <p><b className="text-primary">Unlimited</b> Domain</p>
                            <p><b className="text-primary">No</b> Hidden Fees</p>
                        </div>
                        <a href="#" className="btn btn-primary waves-effect waves-light mt-5">Join Now</a>
                    </div>
                </div>
            </div>
        </div>
    </section> */}
 </div>
 )
}
